language: node_js
node_js:
  - "10"
  - "12"
cache: yarn

jobs:
  include:
    - stage: build
      script:
        - "yarn global add gatsby"
        - "yarn build"
    - stage: deploy
      script:
        - "yarn global add firebase-tools"
        - "yarn global add gatsby"
        - "yarn build"
        - "firebase deploy --token=${FIREBASE_API_TOKEN}"

stages:
  - name: "build"
    if: type = pull_request
  - name: "deploy"
    if: branch = master