language: node_js
node_js:
  - "10"
cache: yarn

branches:
  only:
    - master
before_deploy:
  - "yarn global add firebase-tools"
  - "yarn global add gatsby"
  - "yarn build"
deploy:
  provider: script
  script: "firebase deploy --token=${FIREBASE_API_TOKEN}"
  on:
    branch: master